version: '3.8'

services:
  db:
    image: postgres:17
    container_name: telegram_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: Barabulka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Barabulka
      DB_USER: postgres
      DB_PASSWORD: 123123
    # для продакшена volume не нужен, используем то, что в образе
    # если хочешь live‑разработку — можно вернуть:
    # volumes:
    #   - .:/app
    command: python app.py

volumes:
  postgres_data:
